language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8"
  - "3.8-dev"
install:
  - pip install -r requirements-dev.txt --no-cache
script: pytest
